# Generated by Django 4.0.4 on 2022-05-01 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_recipebusiness_ingredient_is_delete_recipe_is_delete_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecipeBusiness',
        ),
        migrations.CreateModel(
            name='RecipeProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('recipe.recipe',),
        ),
    ]
